module.exports = {
  compilerOptions: {
    strict: true,
    target: 'ES2020',
    module: 'CommonJS',
    moduleResolution: 'node',
    allowSyntheticDefaultImports: true,
    useDefineForClassFields: true,
    esModuleInterop: true,
    pretty: true,
    newLine: 'lf',
    stripInternal: true,
    noImplicitReturns: true,
    noUnusedLocals: true,
    noUnusedParameters: true,
    noFallthroughCasesInSwitch: true,
    noEmitOnError: true,
    forceConsistentCasingInFileNames: true,
    skipLibCheck: true,
    experimentalDecorators: true,
    allowJs: true,
    jsx: 'react-jsx',
    outDir: './dist',
  },
};
